//! Standard Webhooks signature verification — cross-implementation parity.
//!
//! The expected signature headers below were generated by the ACTUAL TypeScript
//! signer (`packages/contracts/src/webhook-signing.ts`, via its byte-for-byte
//! copy `sdks/webhook-ingester/src/webhook-signing.ts`) so this Rust
//! implementation is checked against the real platform output, not against
//! itself. They are the same vectors the Python SDK pins
//! (`sdks/python/tests/test_webhook_signing.py`).

use mailtea::{sign_webhook, verify_webhook_signature_with, VerifyOptions};

const SECRET_A: &str = "whsec_dGVzdC1zaWduaW5nLWtleS0zMi1ieXRlcy1sb25n";
/// A DIFFERENT secret, for the rotation cases. Note the missing base64 padding:
/// the decoder has to tolerate it, because the platform mints secrets this way.
const SECRET_B: &str = "whsec_cm90YXRpb24tc2VjcmV0LTMyLWJ5dGVzLWxvbmctdGVzdA";
const MSG_ID: &str = "msg_2xyzABC123";
const TIMESTAMP: i64 = 1_700_000_000;
const PAYLOAD: &str =
    r#"{"id":"evt_test","type":"email.delivered","data":{"email_id":"txemail_1"}}"#;

const HEADER_A: &str = "v1,txVPz2dd9nKoJKXT5SM0Ryfb0Tb5H+HRpz4nI/xpw+Q=";
const HEADER_B: &str = "v1,c1hy0+MUcGBKxkM1Y96IQmkXAe2lGJY2AeZIQvKBJvg=";

/// The clock pinned to the signing instant, so these never age out.
fn at(now: i64) -> VerifyOptions {
    VerifyOptions {
        now: Some(now),
        ..Default::default()
    }
}

fn verify(secret: &str, payload: &str, header: &str, now: i64) -> bool {
    verify_webhook_signature_with(secret, MSG_ID, TIMESTAMP, payload, header, &at(now))
}

// --- cross-implementation: the Rust signer reproduces the TS output exactly ---

#[test]
fn sign_matches_the_typescript_vector() {
    assert_eq!(sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD), HEADER_A);
    assert_eq!(sign_webhook(SECRET_B, MSG_ID, TIMESTAMP, PAYLOAD), HEADER_B);
}

#[test]
fn sign_then_verify_round_trips() {
    let header = sign_webhook(SECRET_A, MSG_ID, TIMESTAMP, PAYLOAD);
    assert!(verify(SECRET_A, PAYLOAD, &header, TIMESTAMP));
}

#[test]
fn verify_accepts_the_typescript_signed_header() {
    assert!(verify(SECRET_A, PAYLOAD, HEADER_A, TIMESTAMP));
}

#[test]
fn verify_accepts_a_string_timestamp() {
    // The webhook-timestamp header arrives as a string.
    assert!(verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        "1700000000",
        PAYLOAD,
        HEADER_A,
        &at(TIMESTAMP),
    ));
}

// --- bad signature rejected ---

#[test]
fn verify_rejects_a_tampered_payload() {
    // One trailing space is the whole difference.
    assert!(!verify(
        SECRET_A,
        &format!("{PAYLOAD} "),
        HEADER_A,
        TIMESTAMP
    ));
    assert!(!verify(
        SECRET_A,
        r#"{"id":"evt_test","type":"email.bounced"}"#,
        HEADER_A,
        TIMESTAMP
    ));
}

#[test]
fn verify_rejects_the_wrong_secret() {
    // HEADER_A was signed with SECRET_A; verifying with SECRET_B must fail.
    assert!(!verify(SECRET_B, PAYLOAD, HEADER_A, TIMESTAMP));
}

#[test]
fn verify_rejects_a_signature_that_differs_by_one_byte() {
    // The comparison is `hmac::Mac::verify_slice`, which diffs the whole digest
    // in constant time — a near-miss takes exactly as long to reject as a miss.
    let mut tampered = HEADER_A.to_string();
    let last = tampered.pop().unwrap();
    tampered.push(if last == 'A' { 'B' } else { 'A' });
    assert!(!verify(SECRET_A, PAYLOAD, &tampered, TIMESTAMP));
}

#[test]
fn verify_rejects_garbage_and_a_missing_version() {
    assert!(!verify(SECRET_A, PAYLOAD, "", TIMESTAMP));
    assert!(!verify(SECRET_A, PAYLOAD, "not-a-signature", TIMESTAMP));
    // Right signature bytes but a version other than v1 is ignored.
    let wrong_version = format!("v2,{}", HEADER_A.split_once(',').unwrap().1);
    assert!(!verify(SECRET_A, PAYLOAD, &wrong_version, TIMESTAMP));
    // Base64 that does not decode is a `false`, never a panic.
    assert!(!verify(SECRET_A, PAYLOAD, "v1,!!!!", TIMESTAMP));
}

// --- expired / replay ---

#[test]
fn verify_rejects_an_expired_timestamp() {
    assert!(!verify(SECRET_A, PAYLOAD, HEADER_A, TIMESTAMP + 10_000));
    // Replay protection cuts both ways: a delivery from the future fails too.
    assert!(!verify(SECRET_A, PAYLOAD, HEADER_A, TIMESTAMP - 10_000));
}

#[test]
fn verify_rejects_a_timestamp_that_is_not_a_number() {
    assert!(!verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        "not-a-timestamp",
        PAYLOAD,
        HEADER_A,
        &at(TIMESTAMP),
    ));
    assert!(!verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        f64::INFINITY,
        PAYLOAD,
        HEADER_A,
        &at(TIMESTAMP),
    ));
}

/// `webhook-timestamp` arrives from the network, so an absurd value has to be a
/// `false` like any other bad header. Naive `(now - seconds).abs()` panics on
/// `i64::MIN` wherever overflow checks are on — a debug build, or a release
/// profile with `overflow-checks = true`.
#[test]
fn verify_rejects_an_extreme_timestamp_without_panicking() {
    for timestamp in [i64::MIN, i64::MIN + 1, i64::MAX] {
        assert!(!verify_webhook_signature_with(
            SECRET_A,
            MSG_ID,
            timestamp,
            PAYLOAD,
            HEADER_A,
            &at(TIMESTAMP),
        ));
    }

    // The same edge from the other side: a huge tolerance must not make the
    // comparison itself overflow.
    assert!(!verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        i64::MIN,
        PAYLOAD,
        HEADER_A,
        &VerifyOptions {
            now: Some(TIMESTAMP),
            tolerance_seconds: i64::MAX,
        },
    ));

    // And it is the string form that actually arrives on the wire.
    assert!(!verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        "-9223372036854775808",
        PAYLOAD,
        HEADER_A,
        &at(TIMESTAMP),
    ));
}

// --- rotation: a header carrying both tokens verifies against either secret ---

#[test]
fn verify_accepts_either_token_during_rotation() {
    let rotation = format!("{HEADER_A} {HEADER_B}");
    // The endpoint still holds the OLD secret (A): the first token matches.
    assert!(verify(SECRET_A, PAYLOAD, &rotation, TIMESTAMP));
    // The endpoint holds the NEW secret (B): the second token matches.
    assert!(verify(SECRET_B, PAYLOAD, &rotation, TIMESTAMP));
}

// --- tolerance boundary ---

#[test]
fn the_default_tolerance_is_five_minutes_each_way() {
    assert_eq!(mailtea::DEFAULT_TOLERANCE_SECONDS, 300);
    assert!(verify(SECRET_A, PAYLOAD, HEADER_A, TIMESTAMP + 300));
    assert!(!verify(SECRET_A, PAYLOAD, HEADER_A, TIMESTAMP + 301));
}

#[test]
fn the_tolerance_is_configurable() {
    assert!(verify_webhook_signature_with(
        SECRET_A,
        MSG_ID,
        TIMESTAMP,
        PAYLOAD,
        HEADER_A,
        &VerifyOptions {
            tolerance_seconds: 10_000,
            now: Some(TIMESTAMP + 5_000),
        },
    ));
}
